kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: frontend
    project: expense
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: frontend
  # pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: expense
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: prathyusha589/frontend:v1.0

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: expense
    tier: frontend
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port